namespace OhioBox.Moranbernate.Mapping
{
	public class IdOptions
	{
		internal IdOptions(Property property)
		{
			GeneratedBy = new IdOptionsSelector(property);
		}

		public IdOptionsSelector GeneratedBy { get; private set; }
	}

	public class IdOptionsSelector
	{
		private readonly Property _property;

		internal IdOptionsSelector(Property property)
		{
			_property = property;
			_property.Update = false;
			_property.Insert = false;
		}

		/// <summary>
		/// This is the default
		/// </summary>
		public void AutoGenerated()
		{
		}

		public void Assigned()
		{
			_property.Update = true;
			_property.Insert = true;
		}
	}
}